version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "workflow-templates"
    schedule:
      interval: "daily"
    target-branch: "nightly"
    open-pull-requests-limit: 10
  - package-ecosystem: "github-actions"
    directory: "github/workflows"
    schedule:
      interval: "daily"
    target-branch: "nightly"
    open-pull-requests-limit: 10
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "nightly"
    open-pull-requests-limit: 10
