# https://github.com/marketplace/actions/repo-file-sync-action

group:
  # dependabot
  - files:
      - source: github/dependabot/pip.yml
        dest: .github/dependabot.yml
    repos: |
      RetroArcher/RetroArcher.dats@nightly
      RetroArcher/RetroArcher.discord-bot@nightly
      RetroArcher/RetroArcher.reddit-bot@nightly
      RetroArcher/RetroArcher.X@nightly

  # workflows and workflow configs
  - files:
      - source: github/workflows/issues.yml
        dest: .github/workflows/issues.yml
      - source: github/workflows/issues-stale.yml
        dest: .github/workflows/issues-stale.yml
      - source: github/workflows/pull-requests.yml
        dest: .github/workflows/pull-requests.yml
      - source: github/label-actions.yml
        dest: .github/label-actions.yml
    repos: |
      RetroArcher/RetroArcher.branding@nightly
      RetroArcher/RetroArcher.bundle@nightly
      RetroArcher/RetroArcher.client.windows@nightly
      RetroArcher/RetroArcher.database@nightly
      RetroArcher/RetroArcher.dats@nightly
      RetroArcher/RetroArcher.discord-bot@nightly
      RetroArcher/RetroArcher.github.io@nightly
      RetroArcher/RetroArcher.proxy@nightly
      RetroArcher/RetroArcher.reddit-bot@nightly
      RetroArcher/RetroArcher.server.installer@nightly
      RetroArcher/RetroArcher.start-videos@nightly
      RetroArcher/RetroArcher.X@nightly
  
  # workflows/release_notifier
  - files:
      - source: github/workflows/release_notifier.yml
        dest: .github/workflows/release_notifier.yml
    repos: |
      RetroArcher/RetroArcher.bundle@nightly
      RetroArcher/RetroArcher.client.windows@nightly
      RetroArcher/RetroArcher.server.installer@nightly
      RetroArcher/RetroArcher.X@nightly

  # custom issue templates
  - files:
      - source: github/ISSUE_TEMPLATE/retroarcher-x.md
        dest: .github/ISSUE_TEMPLATE/bug-report.md
    repos: |
      RetroArcher/RetroArcher.X@nightly

  # Licenses
  - files:
      - source: LICENSES/GPL-3.0 License
        dest: LICENSE
    repos: |
      RetroArcher/RetroArcher.discord-bot@nightly
      RetroArcher/RetroArcher.proxy@nightly
      RetroArcher/RetroArcher.reddit-bot@nightly
      RetroArcher/RetroArcher.X@nightly
  - files:
      - source: LICENSES/AGPL-3.0 License
        dest: LICENSE
    repos: |
      RetroArcher/RetroArcher.bundle@nightly
      RetroArcher/RetroArcher.client.windows@nightly
      RetroArcher/RetroArcher.server.installer@nightly
  - files:
      - source: LICENSES/MIT
        dest: LICENSE
    repos: |
      RetroArcher/RetroArcher.github.io@nightly
      RetroArcher/RetroArcher.dats@nightly
  - files:
      - source: LICENSES/CC BY-NC-ND
        dest: LICENSE
    repos: |
      RetroArcher/RetroArcher.branding@nightly
  - files:
      - source: LICENSES/CC BY-NC-SA
        dest: LICENSE
    repos: |
      RetroArcher/RetroArcher.database@nightly
      RetroArcher/RetroArcher.start-videos@nightly
