name: Release Notifications

on:
  release:
    types: [published]
    # https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#onevent_nametypes

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: discord
        uses: sarisia/actions-status-discord@v1  # https://github.com/sarisia/actions-status-discord
        with:
          webhook: ${{ secrets.DISCORD_RELEASE_WEBHOOK }}
          username: ${{ secrets.DISCORD_USERNAME }}
          avatar_url: ${{ secrets.ORG_LOGO_URL }}
          title: ${{ github.event.repository.name }} ${{ github.ref }} Released
          description: ${{ github.event.release.body }}
          color: 0xFF4500

      - name: reddit
        uses: bluwy/release-for-reddit-action@v1  # https://github.com/bluwy/release-for-reddit-action
        with:
          username: ${{ secrets.REDDIT_USERNAME }}
          password: ${{ secrets.REDDIT_PASSWORD }}
          app-id: ${{ secrets.REDDIT_CLIENT_ID }}
          app-secret: ${{ secrets.REDDIT_CLIENT_SECRET }}
          subreddit: ${{ secrets.REDDIT_SUBREDDIT }}  # Submit to /r/RetroArcher
          title: ${{ github.event.repository.name }} ${{ github.ref }} Released
          url: ${{ github.event.release.html_url }}
          flair-id: 2c5c66f8-627d-11eb-b58f-0eb22ac1892b  # https://www.reddit.com/r/retroarcher/api/link_flair.json
          comment: ${{ github.event.release.body }}

      - name: twitter
        uses: ethomson/send-tweet-action@v1  # https://github.com/ethomson/send-tweet-action
        with:
          consumer-key: ${{ secrets.TWITTER_API_KEY }}
          consumer-secret: ${{ secrets.TWITTER_API_SECRET }}
          access-token: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          access-token-secret: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
          status: ${{ github.event.release.html_url }}
