name: "Create Release"
description: "Verify changelog was updated and Create Release."
inputs:
  token:
    description: 'Github Token.'
    required: true
  next_version:
    description: 'The version to create.'
    required: true
  last_version:
    description: 'The last released version.'
    required: true
  release_body:
    description: 'The body of the release.'
    required: true

runs:
  using: "composite"
  steps:
    - name: Verify Release Versions
      if: ${{ inputs.next_version == inputs.last_version }}
      # fail the workflow because the versions match
      shell: bash
      run: |
        exit 1

    - name: Create/Update GitHub Release
      if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
      uses: ncipollo/release-action@v1  # https://github.com/ncipollo/release-action
      with:
        name: ${{ inputs.next_version }}
        tag: ${{ inputs.next_version }}
        artifacts: "*artifacts/*"
        token: ${{ inputs.token }}
        allowUpdates: true
        body: ${{ inputs.release_body }}
        discussionCategory: announcements
