---
# Audit repositories in this org.

name: Audit Repos
permissions: {}

on:
  schedule:
    - cron: '00 09 * * *'
  workflow_dispatch:

jobs:
  audit:
    name: Audit Repos
    permissions: {}
    runs-on: ubuntu-latest
    steps:
      - name: Audit
        uses: LizardByte/actions/actions/audit_repos@25babf9f2e9f088145ba488339c78c4df9394fc7  # v2026.524.145234
        with:
          allowEmptyDescription: true
          checkDiscussions: org
          orgDiscussionsRepo: community
          token: ${{ secrets.GH_BOT_TOKEN }}
