---
# Audit repositories in this org.

name: Audit Repos
permissions: {}

on:
  schedule:
    - cron: '00 09 * * *'
  workflow_dispatch:

jobs:
  audit:
    name: Audit Repos
    permissions: {}
    runs-on: ubuntu-latest
    steps:
      - name: Audit
        uses: LizardByte/actions/actions/audit_repos@d0ae7f82215a479fe2b74f4088c53ee6460513dd  # v2026.728.214955
        with:
          allowEmptyDescription: true
          checkDiscussions: org
          orgDiscussionsRepo: community
          token: ${{ secrets.GH_BOT_TOKEN }}
