---
name: Release Notifications (called)
permissions:
  contents: read

on:
  workflow_call:
    secrets:
      GH_EMAIL:
        description: 'GitHub email to use for the workflow.'
        required: true
      GH_NAME:
        description: 'GitHub name to use for the workflow.'
        required: true
      GH_TOKEN:
        description: 'GitHub token to use for the workflow.'
        required: true

jobs:
  update-blog:
    name: Update blog
    if: github.repository_owner == 'LizardByte'
    runs-on: ubuntu-latest
    steps:
      - name: Check topics
        env:
          TOPIC: replicator-release-notifications
        id: check-label
        uses: actions/github-script@v7
        with:
          script: |
            const topic = process.env.TOPIC;
            console.log(`Checking if repo has topic: ${topic}`);

            const repoTopics = await github.rest.repos.getAllTopics({
              owner: context.repo.owner,
              repo: context.repo.repo
            });
            console.log(`Repo topics: ${repoTopics.data.names}`);

            const hasTopic = repoTopics.data.names.includes(topic);
            console.log(`Has topic: ${hasTopic}`);

            core.setOutput('hasTopic', hasTopic);

      - name: Check if latest GitHub release
        id: check-release
        if: steps.check-label.outputs.hasTopic == 'true'
        uses: actions/github-script@v7
        with:
          script: |
            const latestRelease = await github.rest.repos.getLatestRelease({
              owner: context.repo.owner,
              repo: context.repo.repo
            });

            core.setOutput('isLatestRelease', latestRelease.data.tag_name === context.payload.release.tag_name);

      - name: Checkout blog
        if: >-
          steps.check-label.outputs.hasTopic == 'true' &&
          steps.check-release.outputs.isLatestRelease == 'true'
        uses: actions/checkout@v5
        with:
          repository: "LizardByte/LizardByte.github.io"

      - name: Create blog post
        if: >-
          steps.check-label.outputs.hasTopic == 'true' &&
          steps.check-release.outputs.isLatestRelease == 'true'
        run: |
          # setup variables
          tag_name="${{ github.event.release.tag_name }}"
          semver="${tag_name#v}"
          repo_lower="$(echo "${{ github.event.repository.name }}" | tr '[:upper:]' '[:lower:]')"

          # extract year, month, and day
          year="${semver%%.*}"
          month_day="${semver#*.}"
          month_day="${month_day%%.*}"

          # ensure month_day is 4 digits
          month_day=$(printf "%04d" "$month_day")

          # create the filename
          file_name="_posts/releases/${repo_lower}/${year}-${month_day:0:2}-${month_day:2:2}-v${semver}.md"
          mkdir -p "$(dirname "${file_name}")"

          # create jekyll blog post
          {
            echo "---"
            echo "layout: release"
            echo "title: ${{ github.event.repository.name }} ${tag_name} Released"
            echo "release-tag: ${tag_name}"
            echo "gh-repo: ${{ github.repository }}"
            echo "gh-badge: [follow, fork, star]"
            echo "tags: [release, ${repo_lower}]"
            echo "comments: true"
            echo "author: LizardByte-bot"
            echo "---"
            echo ""
          } > "${file_name}"

          release_body=$(cat <<EOF
          ${{ github.event.release.body }}
          EOF
          )

          echo "${release_body}" >> "${file_name}"

      - name: Create/Update Pull Request
        id: create-pr
        if: >-
          steps.check-label.outputs.hasTopic == 'true' &&
          steps.check-release.outputs.isLatestRelease == 'true'
        uses: peter-evans/create-pull-request@v7
        with:
          author: "${{ secrets.GH_NAME }} <${{ secrets.GH_EMAIL }}>"
          committer: "${{ secrets.GH_NAME }} <${{ secrets.GH_EMAIL }}>"
          token: ${{ secrets.GH_TOKEN }}
          commit-message: |
            chore: Add blog post for ${{ github.event.repository.name }} release ${{ github.event.release.tag_name }}
          branch: bot/add-${{ github.event.repository.name }}-${{ github.event.release.tag_name }}
          delete-branch: true
          title: |
            chore: Add blog post for ${{ github.event.repository.name }} release ${{ github.event.release.tag_name }}
          body: ${{ github.event.release.body }}
          labels:
            blog

      - name: Automerge PR
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        if: >-
          steps.check-label.outputs.hasTopic == 'true' &&
          steps.check-release.outputs.isLatestRelease == 'true'
        run: |
          gh pr merge \
            --auto \
            --delete-branch \
            --repo "LizardByte/LizardByte.github.io" \
            --squash \
            "${{ steps.create-pr.outputs.pull-request-number }}"
