---
# This workflow does not need to be replicated to other repositories. This workflow will update the cla gist files
# required for CLA Assistant.

name: CLA gist replicator
permissions: {}

on:
  push:
    branches:
      - master
    paths:
      - "legal/cla/**"
  workflow_dispatch:

jobs:
  replicate_cla:
    name: Replicate CLA
    permissions:
      contents: read
    runs-on: ubuntu-latest
    environment:
      name: cla-gist
      url: https://gist.github.com/${{ vars.CLA_GIST_ID }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1

      - name: Deploy CLA (indivdual)
        uses: exuanbo/actions-deploy-gist@47697fceaeea2006a90594ee24eb9cd0a1121ef8  # v1.1.4
        with:
          token: ${{ secrets.GH_BOT_TOKEN }}
          gist_id: ${{ vars.CLA_GIST_ID }}
          file_path: legal/cla/CLA
          file_type: text

      - name: Deploy CLA (entity)
        uses: exuanbo/actions-deploy-gist@47697fceaeea2006a90594ee24eb9cd0a1121ef8  # v1.1.4
        with:
          token: ${{ secrets.GH_BOT_TOKEN }}
          gist_id: ${{ vars.CLA_GIST_ID }}
          file_path: legal/cla/CLA-entity
          file_type: text

      - name: Deploy CLA (metadata)
        uses: exuanbo/actions-deploy-gist@47697fceaeea2006a90594ee24eb9cd0a1121ef8  # v1.1.4
        with:
          token: ${{ secrets.GH_BOT_TOKEN }}
          gist_id: ${{ vars.CLA_GIST_ID }}
          file_path: legal/cla/metadata
          file_type: text
