---
name: Issue/PR Comment

on:
  repository_dispatch:
    types: [issue-pr-comment]

jobs:
  issue_comment:
    name: Issue/PR Comment
    if: ${{ github.event_name == 'repository_dispatch' }}
    runs-on: ubuntu-latest
    permissions:
      issues: write  # required to add issue comment
      pull-requests: write  # required to add PR comment
    steps:

      - name: Issue Comment
        uses: mshick/add-pr-comment@v2
        with:
          issue: ${{ github.event.client_payload.issue_number }}
          repo-token: ${{ secrets.GH_BOT_TOKEN }}
          message: ${{ github.event.client_payload.issue_message }}
          message-id: ${{ github.event.client_payload.issue_message_id }}
