---
name: Issue/PR Comment

on:
  workflow_dispatch:
    inputs:
      issue_message:
        description: 'Issue/PR comment message'
        required: true
      issue_message_id:
        description: 'Issue/PR comment message id'
        required: true
      issue_number:
        description: 'Issue/PR number'
        required: true
      issue_repo_owner:
        description: 'Issue/PR repo owner'
        required: true
      issue_repo_name:
        description: 'Issue/PR repo name'
        required: true

jobs:
  issue_comment:
    name: Issue/PR Comment
    runs-on: ubuntu-latest
    permissions:
      issues: write  # required to add issue comment
      pull-requests: write  # required to add PR comment
    steps:

      - name: Issue Comment
        # uses: mshick/add-pr-comment@v2
        # todo - testing ability to comment on another repo
        uses: ReenigneArcher/add-pr-comment@add-custom-owner-and-repo-inputs
        with:
          issue: ${{ github.event.inputs.issue_number }}
          repo-owner: ${{ github.event.inputs.issue_repo_owner }}
          repo-name: ${{ github.event.inputs.issue_repo_name }}
          repo-token: ${{ secrets.GH_BOT_TOKEN }}
          message: ${{ github.event.inputs.issue_message }}
          message-id: ${{ github.event.inputs.issue_message_id }}
