---
# This workflow does not need to be replicated to other repositories. This workflow will update the files in other org
# repos. Currently, this workflow will only run on a workflow dispatch event. Once a solution is made to use the same
# PR branch for updates we can enable updating on push events into `master` branch.

name: Global replicator

on:
  push:
    branches: [master]  # only files that were changed in the commit will be replicated
  workflow_dispatch:
    inputs:
      repo_name:
        description: |
          You can specify the repository's name where workflows should be pushed manually, as long as workflow settings
          do not ignore the repository. If you do not specify the exact repository name, the workflow will try to
          replicate all missing changes to all repositories.
        required: false

jobs:
  replicate:
    runs-on: ubuntu-latest
    name: Replicate files

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Removing files
        uses: derberg/manage-files-in-multiple-repositories@v2.1.0
        with:
          github_token: ${{ secrets.GH_BOT_TOKEN }}
          committer_username: ${{ secrets.GH_BOT_NAME }}
          committer_email: ${{ secrets.GH_BOT_EMAIL }}
          patterns_to_ignore: ''
          patterns_to_remove: >-
            .github/workflows/autoupdate.yml,
            .github/workflows/autoupdate-labeler.yml,
            .github/workflows/ci-qodana.yml,
            .github/workflows/dispatcher.yml,
            .github/workflows/pull-requests.yml,
            qodana-dotnet.yaml,
            qodana-js.yaml,
            qodana-python.yaml
          commit_message: 'chore: update global workflows'
          repos_to_ignore: ''
          topics_to_include: ''
          exclude_private: false
          exclude_forked: true
          destination: ''
          bot_branch_name: bot/update-files-from-global-repo

      # checkout between each step to ensure we have a clean GitHub workspace
      # see https://github.com/derberg/manage-files-in-multiple-repositories/issues/61#issuecomment-1747013728
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Replicating files (general)
        uses: derberg/manage-files-in-multiple-repositories@v2.1.0
        with:
          github_token: ${{ secrets.GH_BOT_TOKEN }}
          committer_username: ${{ secrets.GH_BOT_NAME }}
          committer_email: ${{ secrets.GH_BOT_EMAIL }}
          patterns_to_ignore: ''
          patterns_to_include: >-
            .github/dependabot.yml,
            .github/label-actions.yml,
            .github/pr_release_template.md,
            .github/workflows/auto-create-pr.yml,
            .github/workflows/automerge.yml,
            .github/workflows/autoupdate.yml,
            .github/workflows/autoupdate-labeler.yml,
            .github/workflows/codeql.yml,
            .github/workflows/issues.yml,
            .github/workflows/issues-stale.yml,
            .github/workflows/yaml-lint.yml
          commit_message: 'chore: update global workflows'
          repos_to_ignore: ''
          topics_to_include: ''
          exclude_private: false
          exclude_forked: true
          destination: ''
          bot_branch_name: bot/update-files-from-global-repo

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Replicating files (python)
        uses: derberg/manage-files-in-multiple-repositories@v2.1.0
        with:
          github_token: ${{ secrets.GH_BOT_TOKEN }}
          committer_username: ${{ secrets.GH_BOT_NAME }}
          committer_email: ${{ secrets.GH_BOT_EMAIL }}
          patterns_to_ignore: ''
          patterns_to_include: >-
            .flake8,
            .github/workflows/python-flake8.yml
          commit_message: 'chore: update global workflows'
          repos_to_ignore: ''
          topics_to_include: 'python'
          exclude_private: false
          exclude_forked: true
          destination: ''
          bot_branch_name: bot/update-files-from-global-repo

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Replicating files (docker)
        uses: derberg/manage-files-in-multiple-repositories@v2.1.0
        with:
          github_token: ${{ secrets.GH_BOT_TOKEN }}
          committer_username: ${{ secrets.GH_BOT_NAME }}
          committer_email: ${{ secrets.GH_BOT_EMAIL }}
          patterns_to_ignore: ''
          patterns_to_include: >-
            .github/workflows/ci-docker.yml
          commit_message: 'chore: update global workflows'
          repos_to_ignore: ''
          topics_to_include: 'docker'
          exclude_private: false
          exclude_forked: true
          destination: ''
          bot_branch_name: bot/update-files-from-global-repo

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Replicating files (docker)
        uses: derberg/manage-files-in-multiple-repositories@v2.1.0
        with:
          github_token: ${{ secrets.GH_BOT_TOKEN }}
          committer_username: ${{ secrets.GH_BOT_NAME }}
          committer_email: ${{ secrets.GH_BOT_EMAIL }}
          patterns_to_ignore: ''
          patterns_to_include: >-
            .clang-format,
            .github/workflows/cpp-lint.yml
          commit_message: 'chore: update global workflows'
          repos_to_ignore: ''
          topics_to_include: 'cpp'
          exclude_private: false
          exclude_forked: true
          destination: ''
          bot_branch_name: bot/update-files-from-global-repo

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Replicating files (custom issues)
        uses: derberg/manage-files-in-multiple-repositories@v2.1.0
        with:
          github_token: ${{ secrets.GH_BOT_TOKEN }}
          committer_username: ${{ secrets.GH_BOT_NAME }}
          committer_email: ${{ secrets.GH_BOT_EMAIL }}
          patterns_to_ignore: ''
          patterns_to_include: >-
            .github/ISSUE_TEMPLATE/config.yml
          commit_message: 'chore: update global workflows'
          repos_to_ignore: ''
          topics_to_include: 'replicator-custom-issues'
          exclude_private: false
          exclude_forked: true
          destination: ''
          bot_branch_name: bot/update-files-from-global-repo

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Replicating files (release notifier)
        uses: derberg/manage-files-in-multiple-repositories@v2.1.0
        with:
          github_token: ${{ secrets.GH_BOT_TOKEN }}
          committer_username: ${{ secrets.GH_BOT_NAME }}
          committer_email: ${{ secrets.GH_BOT_EMAIL }}
          patterns_to_ignore: ''
          patterns_to_include: >-
            .github/workflows/release-notifier.yml
          commit_message: 'chore: update global workflows'
          repos_to_ignore: ''
          topics_to_include: 'replicator-release-notifications'
          exclude_private: false
          exclude_forked: true
          destination: ''
          bot_branch_name: bot/update-files-from-global-repo
